project:
  type: website
  output-dir: "docs"

website:
  title: "Alimatou Héma"
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "Portfolio"
        file: portfolio.qmd 
      - text: "CV"
        file: cv.qmd
    right:
      - icon: github
        href: https://github.com/ahema-88
      - icon: twitter
        href: https://twitter.com/AlimatouHEMA1
        
format:
  html:
    theme: cosmos
    css: styles.css

editor: visual

